<?php

namespace AppBundle\Repository;

/**
 * AnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalRepository extends \Doctrine\ORM\EntityRepository
{
    
    
    public function findAllFromCountry($countryName)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $query = $qb->select("a")
            ->from("AppBundle:Animal", "a")
            ->innerJoin("a.countries", "c", 'WITH', 'c.name = :name AND c.name != :name')
            ->setParameter("name", $countryName);

        return $query->getQuery()->getResult();
    }


    public function findHeaviest($weight)
    {
        //methode 1 : pour les requetes complexes, pour les requetes optimisées
        /*
        return $this->getEntityManager()->createQuery(
            "SELECT a FROM AppBundle:Animal a WHERE a . weight > :weight"
        )->setParameter("weight", $weight)
            ->getResult();
        */

        //méthode 2-A
        /*
        $qb = $this->getEntityManager()->createQueryBuilder();
        $query = $qb->select("a")
            ->from("AppBundle:Animal", "a")
            ->where("a . weight > :weight")
            ->setParameter("weight", $weight);
        return $query->getQuery()->getResult();
        */

        //méthode 2-B (psychopate)
        $qb = $this->getEntityManager()->createQueryBuilder();
        $query = $qb->select("a")
            ->from("AppBundle:Animal", "a")
            ->where(
                $qb->expr()->gt("a . weight", ":weight")
            )
            ->andWhere(
                $qb->expr()->lt("a . weight", ":weightMax")
            )
            ->setParameter("weight", $weight)
            ->setParameter("weightMax", 20);

        return $query->getQuery()->getResult();


    }
}
