<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsersByNameQuery($nameStart)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $query = $qb->select("u")
            ->from("AppBundle:User", "u")
            ->where(
                $qb->expr()->like("u.login", ":nameStart")
            )
            ->setParameter("nameStart", $nameStart . '%');

        return $query->getQuery()->getResult();
    }

}
