# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"

  #Create a private network with an ip obtained with dhcp service
  config.vm.network "private_network", type: "dhcp"

  #INSTALL DOCKER (jerome)
  #Instruction are explained here : https://docs.docker.com/engine/installation/linux/ubuntulinux/
   config.vm.provision "shell", inline: <<-SHELL

     #install docker
     sudo apt-get update
     sudo apt-get install apt-transport-https ca-certificates
     sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
     sudo echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' >> /etc/apt/sources.list.d/docker.list
     sudo apt-get update
     sudo sudo apt-get install linux-image-extra-$(uname -r)
     sudo apt-get update
     sudo apt-get -y install docker-engine

     #install docker-compose
     sudo curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
     sudo chmod +x /usr/local/bin/docker-compose

  SHELL

end
